### ISSUE TITLE
The code does not work

### ISSUE THREAD

**Issue by adolfoalamo** [saurabhj80/Yik-Yak-Clone#1]
Hi,
I took your course and now I downloaded the complete code and it is not showing anything on the storyboard and when I run it it does not show any just a white screen after the splash screen.  Please advice

**Comment by saurabhj80** [comment]
I checked and everything works fine. In the storyboard -> Document outline. Just click on one of the view controllers or just zoom out in the storyboard. Further switch your parse app id and client key in the AppDelegate

**Comment by adolfoalamo** [comment]
Hi,
Thank you for your quick response. Yes, I add my parse keys but when I run the app on the emulator does not show anything just a the top green menu without any icon and the white list.  Please advice.  Thank you

**Comment by saurabhj80** [comment]
1. Does your database contain data?
2. Are you simulating the location in the simulator? And if you are try simulating the location which is close to the posts stored on Parse

**Comment by adolfoalamo** [comment]
HI,
I can simulate the location because I can't see anything no menu buttons nothing your a green bar on the top and a white screen list. I want to make some post but the app does not have any menu.
